my_string = input('Введите текст: ')
print('Длина вашего текста составляет', len(my_string), 'символов')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print('В вашем тексте было', len(my_string) - len(my_string.replace(' ','')), 'пробела(-ов)')
print(my_string[0])
print(my_string[-1])